export const data = [
  {
    name: 'Campaign ABC',
    objective: 'Brand Awareness',
    audience: 'Audience 1',
    content_name: 'Banner e-shop',
    description: 'My Description',
    updated: 'Aug 18, 2022 12:58PM',
    image: 'https://picsum.photos/200',
    status: 'Live',
  },
  {
    name: 'Campaign DEF',
    objective: 'Brand Awareness',
    audience: 'Audience 1',
    content_name: 'Banner e-shop',
    description: 'My Description',
    updated: 'Aug 18, 2022 12:58PM',
    image: 'https://picsum.photos/200',
    status: 'Pending Approval',
  },
  {
    name: 'Campaign GHI',
    objective: 'Brand Awareness',
    audience: 'Audience 1',
    content_name: 'Banner e-shop',
    description: 'My Description',
    updated: 'Aug 18, 2022 12:58PM',
    image: 'https://picsum.photos/200',
    status: 'Published',
  },
  {
    name: 'Campaign JKL',
    objective: 'Brand Awareness',
    audience: 'Audience 1',
    content_name: 'Banner e-shop',
    description: 'My Description',
    updated: 'Aug 18, 2022 12:58PM',
    image: 'https://picsum.photos/200',
    status: 'Rejected',
  },
  {
    name: 'Campaign MNO',
    objective: 'Brand Awareness',
    audience: 'Audience 1',
    content_name: 'Banner e-shop',
    description: 'My Description',
    updated: 'Aug 18, 2022 12:58PM',
    image: 'https://picsum.photos/200',
    status: 'Draft',
  },
];
