version: '3.8'

services:
  postgresdb:
    image: 'postgres:latest'
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ~/EdotAdsPgData:/var/lib/postgresql/data
    restart: on-failure
