export default {
  icon: {
    ads_dash: require('../assets/icons/ads_dash.png'),
    ads_home: require('../assets/icons/ads_home.png'),
    ads_manage: require('../assets/icons/ads_manage.png'),
    ads_wallet: require('../assets/icons/ads_wallet.png'),
    arrow_down: require('../assets/icons/arrow_down.png'),
    back: require('../assets/icons/back.png'),
    burger: require('../assets/icons/burger.png'),
    checked: require('../assets/icons/checked.png'),
    menu: require('../assets/icons/menu.png'),
    plus: require('../assets/icons/plus.png'),
    close: require('../assets/icons/close.png'),
    edit: require('../assets/icons/edit.png'),
    remove: require('../assets/icons/remove.png'),
    delete_pink: require('../assets/icons/delete_pink.png'),
    check_circle: require('../assets/icons/check_circle.png'),
    leave: require('../assets/icons/leave.png'),
    calendar: require('../assets/icons/calendar.png'),
    filter: require('../assets/icons/filter.png'),
    checkbox: require('../assets/icons/checkbox.png'),
    checkbox_min: require('../assets/icons/checkbox_min.png'),
    uncheck: require('../assets/icons/uncheck.png'),
    delete_circle: require('../assets/icons/delete_circle.png'),
    radio: require('../assets/icons/radio.png'),
    radio_active: require('../assets/icons/radio_active.png'),
    copy_active: require('../assets/icons/copy_active.png'),
    arrow_right: require('../assets/icons/arrow_right.png'),
    arrow_left: require('../assets/icons/arrow_left.png'),
    arrow_right_grey: require('../assets/icons/arrow_right_grey.png'),
    message: require('../assets/icons/message.png'),
    copy: require('../assets/icons/copy.png'),
    trash: require('../assets/icons/trash.png'),
    search: require('../assets/icons/search.png'),
    delete_grey: require('../assets/icons/delete_grey.png'),
    info: require('../assets/icons/info.png'),
    play: require('../assets/icons/play.png'),
    pause: require('../assets/icons/pause.png'),
    detail: require('../assets/icons/detail.png'),
    check_grey: require('../assets/icons/check_grey.png'),
    media: require('../assets/icons/media.png'),
    approval: require('../assets/icons/approval.png'),
  },

  image: {
    confirm: require('../assets/images/confirm.png'),
  },
};
