export const dummyData = [
  {
    id: 1,
    title: 'Campaign ABC',
    status: 'Live',
    objective: 'Brand Awareness',
    date_start: 'Aug 18, 2022',
    date_end: 'Continuous',
    budget_limit: 'IDR 500.000',
    total_duration: '30 Days',
    total_click: '12.000',
    total_conversion: '49',
    total_view: '17.000',
    total_spent: 'IDR 270.000',
    description: 'Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet',
  },
  {
    id: 2,
    title: 'Campaign DEF',
    status: 'Published',
    objective: 'Brand Awareness',
    date_start: 'Aug 18, 2022',
    date_end: 'Continuous',
    budget_limit: 'IDR 500.000',
    total_duration: '30 Days',
    total_click: '12.000',
    total_conversion: '49',
    total_view: '17.000',
    total_spent: 'IDR 270.000',
    description: 'Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet',
  },
  {
    id: 3,
    title: 'Campaign GHI',
    status: 'Rejected',
    objective: 'Brand Awareness',
    date_start: 'Aug 18, 2022',
    date_end: 'Continuous',
    budget_limit: 'IDR 500.000',
    total_duration: '30 Days',
    total_click: '12.000',
    total_conversion: '49',
    total_view: '17.000',
    total_spent: 'IDR 270.000',
    description: 'Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet',
  },
  {
    id: 4,
    title: 'Campaign JKL',
    status: 'Pending Approval',
    objective: 'Brand Awareness',
    date_start: 'Aug 18, 2022',
    date_end: 'Continuous',
    budget_limit: 'IDR 500.000',
    total_duration: '30 Days',
    total_click: '12.000',
    total_conversion: '49',
    total_view: '17.000',
    total_spent: 'IDR 270.000',
    description: 'Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet',
  },
  {
    id: 5,
    title: 'Campaign MNO',
    status: 'Waiting for your approval',
    objective: 'Brand Awareness',
    date_start: 'Aug 18, 2022',
    date_end: 'Continuous',
    budget_limit: 'IDR 500.000',
    total_duration: '30 Days',
    total_click: '12.000',
    total_conversion: '49',
    total_view: '17.000',
    total_spent: 'IDR 270.000',
    description: 'Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet',
  },
  {
    id: 6,
    title: 'Campaign PQR',
    status: 'Paused',
    objective: 'Brand Awareness',
    date_start: 'Aug 18, 2022',
    date_end: 'Continuous',
    budget_limit: 'IDR 500.000',
    total_duration: '30 Days',
    total_click: '12.000',
    total_conversion: '49',
    total_view: '17.000',
    total_spent: 'IDR 270.000',
    description: 'Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet Lorem Ipsum Dolor Sit Amet',
  },
];
